- name: bug
  description: Something isn't working
  color: d73a4a

- name: feature
  description: New feature or request
  color: a2eeef

- name: documentation
  description: Documentation improvement
  color: 0075ca

- name: ci
  description: Continuous integration improvement
  color: 0075ca

- name: testing
  description: Testing improvement
  color: 0075ca