name: release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          pip install poetry
          poetry install
          poetry --version

      - name: Check Poetry Version
        id: check_version
        run: echo ::set-output name=POETRY_VERSION::$(poetry --version)

      - name: Build and Deploy to PyPI
        run: |
          # Add logic to check if the version has changed
          if [[ "${{ steps.check_version.outputs.POETRY_VERSION }}" != "$(poetry --version)" ]]; then
            poetry build
            poetry publish --build
          else
            echo "Poetry version is not different from the previous one. Deploying to testpypi."
            poetry build
            poetry publish --repository testpypi --build
          fi

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Deploy docs
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Deploy docs only after a successful deployment to PyPI, not testpypi
          poetry build
          poetry publish --build
          cd docs
          make html
          echo "Deploying documentation after successful deployment to Pypi."
